# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 06:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import review_conference.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('fullname', models.CharField(max_length=50, verbose_name='全名')),
                ('usertype', models.CharField(choices=[('A', '系统管理员'), ('M', '会议管理员'), ('R', '审查人'), ('D', '设计单位')], default='M', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('ID', models.URLField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_time', models.DateTimeField(verbose_name='提交时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('content', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '专家意见',
                'verbose_name_plural': '专家意见',
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='会议名称')),
                ('equipment_stage', models.CharField(blank=True, choices=[('论证阶段', '论证阶段'), ('方案阶段', '方案阶段'), ('工程研制阶段', '工程研制阶段'), ('设计定型阶段', '设计定型阶段'), ('生产定型阶段', '生产定型阶段')], max_length=20, verbose_name='研制阶段')),
                ('review_name', models.CharField(max_length=100, verbose_name='评审名称')),
                ('begin_date', models.DateTimeField(verbose_name='开始时间')),
                ('end_date', models.DateTimeField(verbose_name='结束时间')),
                ('address', models.CharField(max_length=100, verbose_name='会议地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('profile', models.TextField(blank=True, verbose_name='会议须知')),
            ],
            options={
                'verbose_name': '审查/评审会议',
                'verbose_name_plural': '审查/评审会议',
            },
        ),
        migrations.CreateModel(
            name='ConferenceGroupMember',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('M', '组长'), ('V', '副组长'), ('E', '成员')], max_length=32, verbose_name='职位')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_set', to='review_conference.Conference', verbose_name='审查/评审会议')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('ID', models.URLField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='题目')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
                ('file', models.FileField(blank=True, upload_to=review_conference.models.user_directory_path, verbose_name='文件')),
            ],
            options={
                'verbose_name': '技术文件',
                'verbose_name_plural': '技术文件',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('ID', models.URLField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '技术设备',
                'verbose_name_plural': '技术设备',
            },
        ),
        migrations.CreateModel(
            name='ReviewGroup',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
            ],
            options={
                'verbose_name': '评审组',
                'verbose_name_plural': '评审组',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('ID', models.URLField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_time', models.DateTimeField(verbose_name='提交时间')),
                ('last_update_time', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('content', models.TextField(verbose_name='内容')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_conference.Conference', verbose_name='会议')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_conference.Equipment', verbose_name='技术设备')),
            ],
            options={
                'verbose_name': '评审意见',
                'verbose_name_plural': '评审意见',
            },
        ),
        migrations.CreateModel(
            name='ConferenceManager',
            fields=[
                ('webuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], max_length=4, verbose_name='性别')),
                ('organization', models.CharField(blank=True, max_length=50, verbose_name='工作单位')),
                ('department', models.CharField(blank=True, max_length=50, verbose_name='部门')),
                ('title', models.CharField(blank=True, max_length=20, verbose_name='职务/职称')),
                ('phone', models.CharField(blank=True, max_length=13, verbose_name='电话')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '会议管理员',
                'verbose_name_plural': '会议管理员',
            },
            bases=('review_conference.webuser',),
        ),
        migrations.CreateModel(
            name='DesignOrganization',
            fields=[
                ('webuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('shortname', models.CharField(blank=True, max_length=50, verbose_name='简称')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='单位地址')),
                ('contactor', models.CharField(blank=True, max_length=20, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=13, verbose_name='联系电话')),
                ('profile', models.TextField(blank=True, verbose_name='简介')),
            ],
            options={
                'verbose_name': '研制单位',
                'verbose_name_plural': '研制单位',
            },
            bases=('review_conference.webuser',),
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('webuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], max_length=4, verbose_name='性别')),
                ('type', models.CharField(blank=True, choices=[('主管机关', '主管机关'), ('军事代表', '军事代表'), ('承制单位', '承制单位'), ('承试单位', '承试单位'), ('使用部队', '使用部队')], max_length=10, verbose_name='类别')),
                ('organization', models.CharField(blank=True, max_length=50, verbose_name='工作单位')),
                ('department', models.CharField(blank=True, max_length=50, verbose_name='部门')),
                ('title', models.CharField(blank=True, max_length=20, verbose_name='职务/职称')),
                ('phone', models.CharField(blank=True, max_length=13, verbose_name='电话')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '会议代表',
                'verbose_name_plural': '会议代表',
            },
            bases=('review_conference.webuser',),
        ),
        migrations.CreateModel(
            name='WebAdmin',
            fields=[
                ('webuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], max_length=4, verbose_name='性别')),
                ('organization', models.CharField(blank=True, max_length=50, verbose_name='工作单位')),
                ('department', models.CharField(blank=True, max_length=50, verbose_name='部门')),
                ('title', models.CharField(blank=True, max_length=20, verbose_name='职务/职称')),
                ('phone', models.CharField(blank=True, max_length=13, verbose_name='电话')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '系统管理员',
                'verbose_name_plural': '系统管理员',
            },
            bases=('review_conference.webuser',),
        ),
        migrations.AddField(
            model_name='summary',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评审专家'),
        ),
        migrations.AddField(
            model_name='document',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_of_equipment', to='review_conference.Equipment', verbose_name='技术设备'),
        ),
        migrations.AddField(
            model_name='conferencegroupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_set', to='review_conference.ReviewGroup', verbose_name='评审组'),
        ),
        migrations.AddField(
            model_name='conference',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='document_of', to='review_conference.Document', verbose_name='技术文件'),
        ),
        migrations.AddField(
            model_name='conference',
            name='equipments',
            field=models.ManyToManyField(blank=True, related_name='equipment_of', to='review_conference.Equipment', verbose_name='技术设备'),
        ),
        migrations.AddField(
            model_name='conference',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='group_of', to='review_conference.ReviewGroup', verbose_name='评审组'),
        ),
        migrations.AddField(
            model_name='comment',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_conference.Conference', verbose_name='会议'),
        ),
        migrations.AddField(
            model_name='comment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_conference.Equipment', verbose_name='技术设备'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评审专家'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_conference.DesignOrganization'),
        ),
        migrations.AddField(
            model_name='document',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_of_organization', to='review_conference.DesignOrganization', verbose_name='设计单位'),
        ),
        migrations.AddField(
            model_name='conferencegroupmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_conference.Reviewer', verbose_name='成员'),
        ),
        migrations.AddField(
            model_name='conference',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conference_creator', to='review_conference.ConferenceManager', verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='conference',
            name='last_updater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conference_updater', to='review_conference.ConferenceManager', verbose_name='最后更新人'),
        ),
        migrations.AddField(
            model_name='conference',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='manager_of', to='review_conference.ConferenceManager', verbose_name='会务组'),
        ),
        migrations.AddField(
            model_name='conference',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='reviewer_of', to='review_conference.Reviewer', verbose_name='会议代表'),
        ),
    ]
